config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'menu' => 'static_pages#menu'
  get 'order-now' => 'static_pages#order_now'
  get 'coupons' => 'static_pages#coupons'
  get 'contacts' => 'static_pages#contacts'

  get 'dashboard' => 'admin#dashboard'

  post 'login'  => 'sessions#create'
  get  'adminpanel'  => 'sessions#admin'
  get  'logout' => 'sessions#destroy'
  
  
  resources :coupons, except: [:index]
  resources :galeries
  resources :categories do 
    resources :products
  end

end

app/views/admin/_categories.html.erb
	<h3  style='margin-bottom: 10px'>Category</h3>
	<%= link_to "New Category", new_category_path, remote: true, class: 'new_category_button'%>
	<hr>
	<div id='categories'>
		<% @categories.each do |c| %>
		<p style='font-size: 20px; color: white;'>
			<%= link_to c.title, dashboard_path(category: c.title)%>
		</p>
		<% end %>
	</div>

app/views/admin/_coupons.html.erb
<h3>Coupons</h3>

	<div class='grid_6'style='color: red'>
		<%= link_to "New Coupons", new_coupon_path, remote: true, class: 'new_coupon_button'%>
	</div>

<table class="grid_12">
	<thead>
		<tr>
			<th> Title </th>
			<th> Description </th>
			<th> Price</th>
			<th colspan="3"> Actions </th>
		</tr>
	</thead>
	<tbody id="coupons">
		<% @coupons.each do |c| %>
		<tr class='coupon_<%= c.id %>'>
			<td> <%= c.title %></td>
			<td> <%= c.desc %></td>
			<td> $<%= c.price %></td>
			<td>
				<%= link_to 'Edit', edit_coupon_path(c), remote: true %>
				<%= link_to 'Destroy', coupon_path(c), method: :delete, remote: true %></li>
			</td>
			
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/_products.html.erb
	<h3><%= @category.title unless @category.nil? %></h3>
	<% unless @category.nil? %>
		<h5 style='color: red'>
			<%= link_to "Add Product To #{@category.title}", new_category_product_path(@category.id), remote: true, class: 'new_product_button'%>
		</h5>
	<% end %>

	<table>
		<thead>
			<tr>
				<th> Image </th>
				<th> Title </th>
				<th> Description </th>
				<th> Price </th>
				<th colspan="3"> Actions </th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |p| %>
			<tr id="products" class='product_<%= p.id %>'>
				<td><%= image_tag(p.image_url :thumb) %></td>
				<td><%= p.title %></td>
				<td><%= p.desc %></td>
				<td>$<%= p.price %></td>
				<td>
				<% unless @category.nil? %>
				    <%= link_to 'Edit', edit_category_product_path(@category.id, p), remote: true %>
    				<%= link_to 'Destroy', category_product_path(@category.id, p), method: :delete, remote: true %></li>
				<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/admin/dashboard.html.erb
<div class="container_12">
<!-- 	<div class="grid_12">
          <nav class='center' style='margin-left: -30px'>
            <ul>
             <li class="bt-icon"><a href="/menu">Categories</a></li>
             <li class="bt-icon" style='margin-right:0px'><a href="/order_now">Coupons</a></li>
             <li class="bt-icon" style='margin-right:0px'><a href="/all_coupons">Users</a></li>
            </ul>
          </nav>
	</div> -->



	<div class="grid_9">
		<%= render 'products' %>
	</div>
		
	<div class="grid_2">
		<%= render 'categories' %>
	</div>

<hr>
	<div class="grid_12">
		<%= render 'coupons' %>
	</div>
</div>