config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'menu' => 'static_pages#menu'
  get 'order-now' => 'static_pages#order_now'
  get 'coupons' => 'static_pages#coupons'
  get 'contacts' => 'static_pages#contacts'

  get 'dashboard' => 'admin#dashboard'

  post 'login'  => 'sessions#create'
  get  'adminpanel'  => 'sessions#admin'
  get  'logout' => 'sessions#destroy'
  
  
  resources :coupons, except: [:index]
  resources :galeries
  resources :categories do 
    resources :products
  end

end

app/views/shared/_auth.html.erb
<hr>
<%= form_for(User.new, remote:true ) do |f| %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name, placeholder: 'First Name' %> <br>

	<%= f.label :last_name %>
	<%= f.text_field :last_name, placeholder: 'Last Name' %> <br>

	<%= f.label :phone %>
	<%= f.text_field :phone, placeholder: '555-555-5555' %> <br>

	<%= f.label :email %>
	<%= f.email_field :email, placeholder: 'email@gmail.com' %> <br>

    <%= f.label :password %>
    <%= f.password_field :password, class: '' %><br>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: '' %>

	<%= f.submit %>
<% end %>


<h1>Login</h1>
<%= form_for :session, url: login_path do |f| %>
	
	<div class="form-group">
		<%= f.label :email %>
		<%= f.email_field :email %>
	</div>

	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="form-group">
		<%= f.submit 'Login' %>
	</div>
<% end %>


<h1>LOG OUT</h1>

<%= link_to "Log Out", logout_path %>


  

app/views/shared/_footer.html.erb
<footer>    
  <div style='margin-bottom: 50px'>
    <a href="https://www.facebook.com/Sola-Pizza-117811531578463/">
      <i class="fa fa-facebook fa-4x"></i>
    </a>

    <a href="https://plus.google.com/105417674240857664711/about">
      <i class="fa fa-google-plus fa-4x" style='margin-left: 30px'></i>
    </a>
  </div>      
  
  <div class="container_12">
    <div class="grid_6 prefix_3">
      <h3 style='font-size: 120px; font-family: Tangerine, serif; color: #4D4B3E; text-align: center; margin-top: -50px' > <a href="/">Sola Pizza </a>
      </h3>
      <!-- <a href="/" class="f_logo"><img src="/assets/img/f_logo.png" alt=""></a> -->
      <div class="copy">

      <!-- &copy; 2013 | <a href="#">Privacy Policy</a> <br> Website   designed by <a href="http://www..com/" rel="nofollow">TemplateMonster.com</a> -->
		&copy; <%= Time.now.year %> Website Developed by <a href="#"><i>7urkm3n</i></a>

      </div>
    </div>
  </div>
</footer>

app/views/shared/_footerjs.html.erb
<script>
  $(document).ready(function(){

      $(".bt-menu-trigger").toggle( 
        function(){
          $('.bt-menu').addClass('bt-menu-open').css();
        }, 
        function(){
          $('.bt-menu').removeClass('bt-menu-open'); 
        } 
      ); 
     
      $().UItoTop({ easingType: 'easeOutQuart' });
  }) 
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74108327-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_indexjs.html.erb
<script>
    $(document).ready(function(){
      $( ".block1" ).mouseover(function() {
        $(this).addClass( "blur" );
      });
      $( ".block1" ).mouseout(function() {
        $(this).removeClass( "blur" );
      });
    }) 
 </script>

app/views/shared/_navbar.html.erb
<header> 
  <div class="container_12">

    <div class="grid_3 center">
      <p style='margin: 70px 100px 0 0'>
        <h2>Address:</h2>
         1417 East Carson Street,
         Pittsburgh, PA 15203
      </p>
      <p>
        <h2>Hours:</h2>
        <b>Mon-Wed: </b>       4:00pm - 12:00am <br>
        <b>Thu-Sat: </b>     4:00pm - 3:00am <br>
        <b style='margin-left: 5px'>Sunday: </b> 4:00pm - 12:00am
      </p>

    </div>

   <div class="grid_6 "> 
      <h3 class='logo logoMain center'> 
        <a href="/">Sola Pizza <p class='logoText'> Fast and Free Delivery</p></a>
      </h3>
      
      <h3 class='center' style='margin-top: -140px'>412-481-3888</h3>
      <div class="menu_block">
        <nav class='center' style='margin-left: -30px'>
            <ul>
             <li class="bt-icon"><a href="/menu" style='color: #FF3030'>Menu</a></li>
             <li class="bt-icon" style='margin-right:0px'><a href="/order-now" style='color: red'>Order Now</a></li>
             <li class="bt-icon" style='margin-right:0px'><a href="/coupons" style='color: red'>Coupons</a></li>
             <li class="bt-icon"><%= link_to "Contacts", contacts_path, style: 'color: red' %> </li>
            </ul>
          </nav>
          <div class="clear"></div>
      </div>

      <% if logged_in? && current_user.admin %>
      <hr>
        <ul style='margin-left: 20%'>
             <li class="bt-icon"><%= link_to "Galery", galeries_path %> </li>
          <li class="bt-icon"><%= link_to "Dashboard", dashboard_path %></li>
          <li class="bt-icon"><%= link_to "Sign Out", logout_path %> </li>
        </ul>
      <% end %>

      <div class="clear"></div>

    </div>  <!-- grid_12 -->
    <div class="grid_3 center">
      <div class='logo logoOrder' >
          <a href="/order-now">Order Online</a>
      </div>      
    </div>
    
  </div> <!-- Container_12 -->
</header>