config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'menu' => 'static_pages#menu'
  get 'order-now' => 'static_pages#order_now'
  get 'coupons' => 'static_pages#coupons'
  get 'contacts' => 'static_pages#contacts'

  get 'dashboard' => 'admin#dashboard'

  post 'login'  => 'sessions#create'
  get  'adminpanel'  => 'sessions#admin'
  get  'logout' => 'sessions#destroy'
  
  
  resources :coupons, except: [:index]
  resources :galeries
  resources :categories do 
    resources :products
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	# before_save { self.title = title.capitalize }
	has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  def index
    @category = Category.new
    @categories = Category.all
  end

  def show
    @products = Product.where(category_id: @category.id)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    
    respond_to do |format|
      if @category.save
        # format.html { redirect_to @category, notice: 'Category was successfully created.' }
        flash[:success] = "#{@category.title} Successfully Added"
        format.js
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        # format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      # format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/views/categories/_category.html.erb
<% blockk do %>
  <tr class='category_<%= category.id %>'>
    <td><%= link_to category.title, category %></td>
    <td><%= link_to "Edit", edit_category_path(category), remote: true, id: 'edit'%></td>
    <td><%= link_to "Delete", category, remote: true, method: :delete %></td>
  </tr>
  <br>
 <% end %>


                    
	<li><%= link_to category.title, "##{category.id}", class: 'category', style: 'color: #FF3030' %></li>
                    

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Category_Title" %><br>
    <%= f.text_field :title, placeholder: 'Pizza/Wings/Sandwich?', autofocus: true, 'data-behavior' => 'submit_on_enter' %>
  </div>
<% end %>

app/views/categories/create.js.erb
console.log("create.js.erb file");
	
	$('nav').after("<div class='alert alert-success'> Successfully Added </div>");
	$('#categories').append("<%= j render @category %>");
	$('form').remove();
	$('.new_category_button').show();


// 2st Step Direct form for button
// $append
// $('#category_title').val("");

app/views/categories/destroy.js.erb
console.log("destroy.js.erb file");
// window.location.replace("http://localhost:3000");

$('nav').after("<div class='alert alert-danger'> Successfully Destroyed </div>");
$(".category_" + <%= @category.id %>).fadeOut(250, function(){
	$(this).remove();
});
	

app/views/categories/edit.js.erb
console.log("edit.js.erb file");
console.log(".category_" + <%= @category.id %> );



$('.category_'+<%= @category.id%>).after("<%= escape_javascript(render 'form') %>");
$('.new_category_button').hide();
console.log("END");
// $('form').slideDown(350);

app/views/categories/index.html.erb
<div class="container_12">
	<%#= render 'form' %>
	<%= link_to "Add Category", new_category_path, remote: true, class: 'new_category_button'%>
</div>

<div class="content"><div class="ic"></div>
  <div class="container_12">
    <div class="grid_12">
      <h3 class="head2">Our Menu</h3>
    </div>  
    
    <div class="tabs tb gallery">
         <div class="div-nav  ">
             <div class="grid_12">
                 <ul class="nav" id='categories'>
                    <!-- <li class="selected"><a href="#tab-2" class="">Salads</a></li> -->
                    <%= render @categories %>
                 </ul>
             </div>    
         </div>
         <div class="div-tabs">
     	<% @categories.each do |c| %>

     		
          <div  id="<%= c.id %>" class="tab-content gallery1">
         	  <div class="clear"></div>
     		<% if c.title.downcase == 'pizza' %>
	     		<p>  </p>
     		<% end %>
          	<% c.products.each do |p| %>
              <div class="grid_3">
                <a href="#" class="gal"><img src="<%= p.image_url %>" alt=""><span></span></a>
                <div class="col2">
                  <span class="col3">
                    <a href="#"><%= p.title %></a>
                  </span> 
                  $ <%= p.price %>
                </div>
              </div>
            <% end %>
            
              <!-- <div class="grid_3">
                <a href="images/big2.jpg" class="gal"><img src="images/page3_img2.jpg" alt=""><span></span></a>
                <div class="col2"><span class="col3"><a href="#">Phasellus erat </a></span> $ 21.99</div>
              </div> -->
          </div>
     	<% end %>
         </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/new.js.erb
console.log('New.js.erb');

$('.new_category_button').after("<%= j render('form') %>");
$('.new_category_button').hide();

// $('.new_category_button').html("<%= j button_tag :cancel %>").on('click', function(){
// 	$('form').remove();
// });

app/views/categories/show.html.erb
<div class="container_12">
<p id="notice"><%= notice %></p>

  <div><h1><%= @category.title %></h1>

<%= link_to 'Add Product', new_category_product_path(@category), remote: true, class: 'new_product_button'%>
<div id="products"></div>
<ul>
<%= render @products %>
</ul>

<br><br>
<br><br>
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/update.js.erb
console.log("Update.js.erb file");

$('nav').after("<div class='alert alert-success'> Successfully Updated </div>");
$(".category_" + <%= @category.id %>).replaceWith("<%= j(render @category) %>");
$('form').remove();
$('.new_category_button').show();