config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'menu' => 'static_pages#menu'
  get 'order-now' => 'static_pages#order_now'
  get 'coupons' => 'static_pages#coupons'
  get 'contacts' => 'static_pages#contacts'

  get 'dashboard' => 'admin#dashboard'

  post 'login'  => 'sessions#create'
  get  'adminpanel'  => 'sessions#admin'
  get  'logout' => 'sessions#destroy'
  
  
  resources :coupons, except: [:index]
  resources :galeries
  resources :categories do 
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = @category.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :back, notice: 'Product was successfully created.' }
        format.js {}
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to :back, notice: 'Product was successfully updated.' }
        format.js {}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.js {}
      # format.html { redirect_to category_products_path, notice: 'Product was successfully destroyed.' }
    end
  end

  private

    def set_category
      @category = Category.find(params[:category_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :desc, :price, :image, :remote_image_url, :category_id)
    end
end

app/views/products/_form.html.erb
<div id="form_field" style='border: 1px solid; border-radius: 7px; margin: 20px 0px'>
<%= form_for [@category, @product] do |f| %>

  <div class="field">
    <%= image_tag(@product.image) if @product.image? %>
    <%#= f.hidden_field :image_cache %>
    <%= f.file_field :image %>
    <br>
    <%= f.text_field :remote_image_url, placeholder: 'Enter URL' %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<button id='cancel' class='btn btn-default'> Cancel </button>

<script>
$(document).ready(function(){

  $('#cancel').on('click', function(){
      $('#form_field').remove();
      $('.new_product_button').show();
  })

});

</script>
</div>

app/views/products/_product.html.erb
<% blockk do %>  
  <ul class='product_<%= product.id %>'>
    <li><%= link_to product.title, category_product_path(@category, product) %>
    <%= product.desc %>
    <%= product.price %>
    <%= image_tag product.image %>
    <%= link_to 'Edit', edit_category_product_path(@category, product), remote: true %>
    <%= link_to 'Destroy', category_product_path(@category, product), method: :delete, remote: true %></li>
  </ul>
 <% end %>


<div class="div-tabs">
  <div id="tab-1" class="tab-content gallery1">
      <div class="grid_3">
        <div class='product_<%= product.id %>'>
        	<%= link_to product.title, class: 'gal' do %>
        		<%= image_tag product.image_url, class: 'gal' %>
        	<% end %>

        	<div class="col2">
            <span class="col3"> <%= product.title %></span> 
             $ <%= product.price %>
             <p>
             <%= link_to 'Edit', edit_category_product_path(@category, product), remote: true %>
             <%= link_to 'Destroy', category_product_path(@category, product), method: :delete, remote: true %></li>
             </p>
          </div>
		    </div>
      </div> <!-- End of Grid -->
  </div>
</div>

app/views/products/create.js.erb
console.log("product| create.js.erb file");
	
	$('nav').after("<div class='alert alert-success'> Product Successfully Added </div>");
	$('#products').append("<%= j render @product %>");
	$('form').remove();
	$('.new_product_button').show();


// 2st Step Direct form for button
// $append
// $('#category_title').val("");

app/views/products/destroy.js.erb
console.log("Product | destroy.js.erb file");

// $('nav').previous("<div class='alert alert-danger'> Successfully Destroyed </div>");
$(".product_" + <%= @product.id %>).fadeOut(250, function(){
	$(this).remove();
});
	

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%#= link_to 'Show', @product %> |
<%#= link_to 'Back', products_path %>

app/views/products/edit.js.erb
console.log("edit.js.erb file");
console.log(".product_" + <%= @product.id %> );


$('.product_'+<%= @product.id%>).after("<%= escape_javascript(render 'form') %>");
$('.new_product_button').hide();
console.log("END");	
// $('form').slideDown(350);

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='products'>
    <%= render @products %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_category_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%#= link_to 'Back', products_path %>

app/views/products/new.js.erb
console.log('New.js.erb');

$('.new_product_button').after("<%= j render('form') %>");

// $('.new_category_button').html("<%= j button_tag :cancel %>").on('click', function(){
// 	$('form').remove();
// });

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%#= link_to 'Edit', edit_product_path(@product) %>
<%#= link_to 'Back', products_path %>